### ISSUE TITLE
SSL problem: An error occurred: SSL certificate problem: unable to get local issuer certificate.

### ISSUE THREAD

**Issue by strietzel** [sensiolabs/security-checker#37]
I am on a windows host:

When I comment out the line 90 in SecurityChecker.php [curl_setopt($curl, CURLOPT_CAINFO, $cert);] my app takes the certificate file specified in my php.ini (curl.cainfo) instead of the one you provided in Ressources dir.
And then it works!

With your file I get the ssl error.
Is your security.sensiolabs.org.crt file not up-to-date?

**Comment by fbourigault** [comment]
I also have the error on my system.

Informations about php:
```
$ php -v
PHP 5.6.9 (cli) (built: May 15 2015 10:24:33) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with blackfire v0.23.0, https://blackfire.io/, by SensioLabs
```

Informations about curl (php use curl shared library):
```
$ curl --version
curl 7.42.0 (x86_64-unknown-linux-gnu) libcurl/7.42.0 OpenSSL/1.0.2a zlib/1.2.8 libidn/1.30 libssh2/1.5.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

Informations about security-checker:
```
$ composer global info -i sensiolabs/security-checker
Changed current directory to /home/fabien/.composer
name     : sensiolabs/security-checker
descrip. : A security checker for your composer.lock
keywords : 
versions : * v2.0.2
type     : library
license  : MIT License (MIT) (OSI approved) http://spdx.org/licenses/MIT#licenseText
source   : [git] https://github.com/sensiolabs/security-checker.git cecb1397087dc9c733796eda6e9d121336039cdc
dist     : [zip] https://api.github.com/repos/sensiolabs/security-checker/zipball/cecb1397087dc9c733796eda6e9d121336039cdc cecb1397087dc9c733796eda6e9d121336039cdc
names    : sensiolabs/security-checker

autoload
psr-0
SensioLabs\Security => .

requires
ext-curl *
symfony/console ~2.0
```

I just tried a GET request on endpoint using curl:

```
$ LANG=C curl -vvv https://security.sensiolabs.org/check_lock --cacert ~/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/Resources/security.sensiolabs.org.crt 
*   Trying 46.137.102.208...
*   Trying 2a01:578:3::b022:e8db...
* Immediate connect fail for 2a01:578:3::b022:e8db: Network is unreachable
*   Trying 2a01:578:3::2e89:66d0...
* Immediate connect fail for 2a01:578:3::2e89:66d0: Network is unreachable
* Connected to security.sensiolabs.org (46.137.102.208) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /home/fabien/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/Resources/security.sensiolabs.org.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
* TLSv1.2, TLS handshake, Client hello (1):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, Server hello (2):
* SSLv2, Unknown (22):
* TLSv1.2, TLS handshake, CERT (11):
* SSLv2, Unknown (21):
* TLSv1.2, TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

Regards

**Comment by fabpot** [comment]
should be fixed in 2.0.3

**Comment by fbourigault** [comment]
Sadly I still have the same error on Arch Linux :/

**Comment by lazyants** [comment]
I still have the same error too. On Yosemite with PHP 5.5.24

**Comment by acrozes** [comment]
+1
Windows / PHP 5.6.4

**Comment by strietzel** [comment]
It sadly seems not to be fixed!.. I still get the error with 2.0.3 :-(

**Comment by pborreli** [comment]
having same error with 2.0.4
```
An error occurred: error setting certificate verify locations:
CAfile: ../vendor/sensiolabs/security-checker/SensioLabs/Security/Resources/security.sensiolabs.org.crt
CApath: /etc/ssl/certs.

**Comment by acrozes** [comment]
+1
but this is a new error ...

**Comment by pborreli** [comment]
@acrozes so it's maybe a regression by #41

**Comment by acrozes** [comment]
@pborreli maybe, I think it is in link with #41

**Comment by fbourigault** [comment]
I also have this new error:

```
An error occurred: error setting certificate verify locations:
  CAfile: /home/fabien/Projets/fbourigault/ouverture/vendor/sensiolabs/security-checker/SensioLabs/Security/Resources/security.sensiolabs.org.crt
  CApath: none.  
```

**Comment by lazyants** [comment]
@acrozes 
no, same problem:

                                           
  An error occurred: error setting certificate verify locations:
  CAfile: vendor/sensiolabs/security-checker/SensioLabs/Security/Resources/security.sensiolabs.org.crt
  CApath: none.

**Comment by acrozes** [comment]
The error is fixed for me with v2.0.5

**Comment by fbourigault** [comment]
Fixed for me too :+1:
